#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2016 Gordon W. Ross
#

include $(SRC)/cmd/Makefile.cmd
include $(SRC)/common/libdrm/Makefile.drm

CPPFLAGS +=	-I$(LIBDRM_CMN_DIR)/tests
CPPFLAGS +=	-I$(LIBDRM_CMN_DIR)

ROOTCMDDIR=$(ROOT)/opt/drm-tests

LIBUTIL32=$(SRC)/cmd/drm-tests/util/i386/libutil.a
LIBUTIL64=$(SRC)/cmd/drm-tests/util/amd64/libutil.a

# We don't really care about warnings in the tests.
CERRWARN +=	-_gcc=-Wno-parentheses
CERRWARN +=	-_gcc=-Wno-uninitialized
