.\"
.\" This file and its contents are supplied under the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.illumos.org/license/CDDL.
.\"
.\"
.\" Copyright 2015 Nexenta Systems, Inc.
.\"
.Dd "Apr 7, 2015"
.Dt FOO 1
.Os
.Sh NAME
.Nm foo
.Nd example command
.Sh SYNOPSIS
.Nm foo
.Op Fl v
.Sh DESCRIPTION
The
.Nm
command is a dummy example for the on-skeleton repository.
It does nothing interesting, other than demonstrate a
command and a library.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl v
Verbose mode.
.El
.Sh SEE ALSO
.Xr foo 3x ,
.Xr foo 7
