.\"
.\" This file and its contents are supplied under the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.illumos.org/license/CDDL.
.\"
.\"
.\" Copyright 2015 Nexenta Systems, Inc.
.\"
.Dd "Apr 7, 2015"
.Dt FOO 7
.Os
.Sh NAME
.Nm foo
.Nd example "foo" driver
.Sh SYNOPSIS
.In sys/foo.h
.Sh DESCRIPTION
The
.Fn foo
driver is a simple example that just implements one
.Xr ioctl 2
function:
.Sy FOO_IOC_GETCNT .
.Sh SEE ALSO
.Xr foo 1 ,
.Xr libfoo 3x
